# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a56ff95af492dfb2049e217de02aa0243e2d38b09b4df83d57576c5004d6cc3e2c191ad86639bbd87ba0f8eb64eac31a681ebfe2a6cd9fe5e8ad0af16acc93

test:
  secret_key_base: b4e5f1dee64dd8eec395d1403ad169e1a1999a49f4b2c63fface5a13fefc7477e86354198c1b1a17bf44bffee8525694a9a5ab31a8a1030ff02462b00f59f114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
